---
application:
  name: "docker-wordpress"
  project: "wordpressTest"
  organization: "QoveryCommunity"
  storage:
  - name: "kruger"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/kruger"
databases:
- type: "MYSQL"
  name: "freddy"
  version: "8.0"
routers:
- name: "main-docker-wordpress"
  routes:
  - application_name: "docker-wordpress"
    paths:
    - "/*"
